# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import datetime
import pathlib
import typing
__all__ = [
    "ArcFile",
]

@typing.final
class ArcFile:
    @property
    def paths(self) -> builtins.list[pathlib.Path]: ...
    @staticmethod
    def load(path: typing.Any, t1: typing.Optional[datetime.datetime] = None, t2: typing.Optional[datetime.datetime] = None, filters: typing.Optional[typing.Sequence[builtins.str]] = None) -> ArcFile: ...
    def to_dict(self) -> dict: ...
    def __getitem__(self, name: builtins.str) -> typing.Any: ...
    def __len__(self) -> builtins.int: ...
    def keys(self) -> typing.Any: ...

