name: Generate docs for core library

on:
  push:
    branches: [master]
    paths:
      - "core/**"
      - "Cargo.toml"
      - "Cargo.lock"
      - "README.md"
      - ".github/workflows/docs.yaml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable

      - name: Generate Rust docs
        run: cargo doc --no-deps --package arcfile

      - name: Adjust documentation for GitHub Pages hosting
        run: echo '<meta http-equiv="refresh" content="0;url=arcfile/index.html">' > target/doc/index.html

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/doc

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
